### PR TITLE
allowing custom scheme for cordova-plugin-ionic-webview

### PR DESCRIPTION
**Pull request by cognitivedesire**
cordova plugin for webview is using custom scheme so the PDF html was not loading in the WebView.

This change allows **ionic:** protocol to be whitelisted

### CODE REVIEW

**Comment by kohlia** [comment]
Hi Can you Please merge the change

**Comment by kohlia** [comment]
Hi @cesarvr can you please publish it to npm
Thank You

**Comment by kohlia** [comment]
Hi @cesarvr can you please publish it as I need to link it to my project

**Comment by cesarvr** [comment]
just published [https://www.npmjs.com/package/cordova-pdf-generator](https://www.npmjs.com/package/cordova-pdf-generator )

Cheers. 👍

**Pull request merged**
